import esbuild from "esbuild";
import process from "process";
import { createRequire } from "module";

const require = createRequire(import.meta.url);
const pkg = require("./package.json");

const banner =
    `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository
*/
`;

const prod = (process.argv[2] === "production");

const context = await esbuild.context({
    banner: {
        js: banner,
    },
    entryPoints: ["src/main.ts"],
    bundle: true,
    platform: "node", // Target node environment (Obsidian has Node integration via require)
    external: [
        "obsidian",
        "electron",
        "@codemirror/*",
        "@lezer/*",
        // Node built-ins
        "http",
        "https",
        "url",
        "crypto",
        "stream",
        "buffer",
        "util",
        "zlib",
        "net",
        "tls",
        "fs",
        "path",
        "string_decoder",
        "events",
        // Handle node: protocol
        "node:*",
        ...Object.keys(pkg.dependencies || {}).filter(x => x.startsWith("@types/")),
    ],
    format: "cjs",
    target: "es2018",
    logLevel: "info",
    sourcemap: prod ? false : "inline",
    treeShaking: true,
    outfile: "main.js",
});

if (prod) {
    await context.rebuild();
    process.exit(0);
} else {
    await context.watch();
}
